# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration
  labels:
    app: configuration
spec:
  selector:
    matchLabels:
      app: configuration
  template:
    metadata:
      labels:
        app: configuration
    spec:
      containers:
      - name: container
        image: vawu/send-card:latest
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: config-app